import { z } from "zod";
import { CLAIM_TYPES } from "@/lib/constants";

/**
 * Broker catalog v2 schema (Sprint 4).
 *
 * The catalog lives in `src/lib/brokers/data/`:
 * - `brokers.json` — hand-curated entries (`source: "curated"`) plus the corporate groups.
 * - `cppa-registry.json` — generated by `scripts/import-cppa-registry.ts` from the checked-in
 *   CPPA registry snapshot (`source: "cppa_registry"`). Never edited by hand.
 * - `id-aliases.json` — old broker id → current id, so stored rows keep resolving after a rename.
 *
 * Research rule: where a value is not known, use `null` or `"unknown"`. Never invent a value
 * (an email address, a URL, a turnaround) to pass validation.
 */

export const BROKER_TYPES = ["data_broker", "people_search", "public_records"] as const;
export type BrokerType = (typeof BROKER_TYPES)[number];

/**
 * How a listing on this broker can be detected:
 * - auto_fetch    — ClearTrace may fetch the broker's own search page server-side.
 * - guided_manual — the user opens the broker's search page (searchUrlTemplate) and checks.
 * - serp_only     — no usable on-site search; listings only surface through search engines.
 * - not_listable  — no consumer-facing listing (B2B / marketing data); only a rights request works.
 */
export const DETECTION_MODES = ["auto_fetch", "guided_manual", "serp_only", "not_listable"] as const;
export type DetectionMode = (typeof DETECTION_MODES)[number];

/**
 * How a removal is requested. "none" = no removal path exists (court / official-record
 * mirrors: request de-indexing instead). "unknown" = research found no working route yet.
 */
export const OPT_OUT_METHODS = ["web_form", "email", "account", "mail", "phone", "none", "unknown"] as const;
export type OptOutMethod = (typeof OPT_OUT_METHODS)[number];

/** active = operating broker; defunct = domain seized / parked / discontinued (kept so old rows resolve). */
export const BROKER_STATUSES = ["active", "defunct"] as const;
export type BrokerStatus = (typeof BROKER_STATUSES)[number];

export const OPT_OUT_SCOPES = ["perListing", "perPerson", "unknown"] as const;
export type OptOutScope = (typeof OPT_OUT_SCOPES)[number];

/** State data-broker registries a broker is known to be registered with. */
export const REGISTRIES = ["ca", "vt", "or", "tx"] as const;
export type Registry = (typeof REGISTRIES)[number];

export const BROKER_SOURCES = ["curated", "cppa_registry"] as const;
export type BrokerSource = (typeof BROKER_SOURCES)[number];

/**
 * Basis a removal request can rest on:
 * - voluntary_policy — the broker offers an opt-out to anyone as a matter of policy.
 * - ccpa             — California Consumer Privacy Act deletion / opt-out rights.
 * - state_privacy    — other US state comprehensive privacy laws (VA, CO, CT, OR, TX, ...).
 * - gdpr             — EU / UK GDPR erasure (residents of those jurisdictions).
 * - fcra             — the broker is (partly) a consumer reporting agency; FCRA dispute rights.
 */
export const LAWFUL_BASES = ["voluntary_policy", "ccpa", "state_privacy", "gdpr", "fcra"] as const;
export type LawfulBasis = (typeof LAWFUL_BASES)[number];

/**
 * Fields an opt-out flow asks for. Identity fields are claim-type ids (src/lib/constants.ts);
 * `listing_url` is the URL of the user's profile/listing on the broker's site.
 */
export const REQUIRED_FIELD_IDS: [string, ...string[]] = [
  "listing_url",
  ...CLAIM_TYPES.map((c) => c.id),
];

/** Placeholders a searchUrlTemplate may use (see search-url.ts). */
export const SEARCH_PLACEHOLDERS = ["first", "last", "full", "city", "state", "cityState"] as const;
export type SearchPlaceholder = (typeof SEARCH_PLACEHOLDERS)[number];

const triState = z.union([z.boolean(), z.literal("unknown")]);

const domainSchema = z
  .string()
  .regex(/^(?!www\.)[a-z0-9-]+(\.[a-z0-9-]+)+$/, "lowercase hostname without www.");

const httpsUrl = z.string().regex(/^https:\/\/[^\s]+$/, "https URL");

const isoDate = z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "YYYY-MM-DD");

export const detectionSchema = z.object({
  mode: z.enum(DETECTION_MODES),
  /** On-site search URL with {first} {last} {full} {city} {state} {cityState} placeholders. */
  searchUrlTemplate: httpsUrl.nullable(),
  /** Regex (string) that matches a profile/listing URL on this broker. */
  profileUrlPattern: z.string().nullable(),
});

export const optOutSchema = z
  .object({
    method: z.enum(OPT_OUT_METHODS),
    url: httpsUrl.nullable(),
    email: z.email().nullable(),
    /** Where the email address was published (URL or document). Required when email is set. */
    emailSource: z.string().nullable(),
    requiredFields: z.array(z.enum(REQUIRED_FIELD_IDS)),
    requiresEmailConfirm: triState,
    requiresPhoneVerify: triState,
    requiresIdUpload: triState,
    hasCaptcha: triState,
    scope: z.enum(OPT_OUT_SCOPES),
  })
  .superRefine((o, ctx) => {
    if (o.email && !o.emailSource) {
      ctx.addIssue({ code: "custom", message: "optOut.email needs an emailSource (no synthesized addresses)" });
    }
    // A form reached from the listing page itself (requiredFields has listing_url) may have no URL.
    const reachedFromListing = o.requiredFields.includes("listing_url");
    if ((o.method === "web_form" || o.method === "account") && !o.url && !reachedFromListing) {
      ctx.addIssue({ code: "custom", message: `optOut.method ${o.method} needs optOut.url` });
    }
    if (o.method === "email" && !o.email) {
      ctx.addIssue({ code: "custom", message: "optOut.method email needs optOut.email" });
    }
  });

export const brokerSchema = z.object({
  id: z.string().regex(/^[a-z0-9][a-z0-9_]*$/),
  name: z.string().min(1),
  domain: domainSchema,
  /** Other hostnames the same controller publishes the same listings on (not sibling brands). */
  aliasDomains: z.array(domainSchema).default([]),
  type: z.enum(BROKER_TYPES),
  status: z.enum(BROKER_STATUSES).default("active"),
  estimatedReach: z.enum(["low", "medium", "high", "unknown"]),
  privacyUrl: httpsUrl.nullable(),
  detection: detectionSchema,
  optOut: optOutSchema,
  expectedTurnaroundDays: z.number().int().positive().nullable(),
  relistIntervalDays: z.number().int().positive().nullable(),
  parentGroup: z.string().nullable(),
  lawfulBasis: z.array(z.enum(LAWFUL_BASES)),
  registries: z.array(z.enum(REGISTRIES)),
  source: z.enum(BROKER_SOURCES),
  /** Where the opt-out facts came from (page checked, guide, registry row). */
  sourceNote: z.string().nullable(),
  /** Date the opt-out facts were last checked, or "unknown" when never re-verified. */
  lastVerifiedAt: z.union([isoDate, z.literal("unknown")]),
  jurisdictionNotes: z.string().nullable(),
});

export type CatalogBroker = z.infer<typeof brokerSchema>;
export type CatalogBrokerInput = z.input<typeof brokerSchema>;

export const groupSchema = z.object({
  id: z.string().regex(/^[a-z0-9][a-z0-9_]*$/),
  name: z.string().min(1),
  /** Corporate / opt-out domains of the group (e.g. a suppression host) — never sibling brands. */
  domains: z.array(domainSchema).min(1),
  sourceNote: z.string().nullable().default(null),
});
export type BrokerGroup = z.infer<typeof groupSchema>;

export const curatedCatalogSchema = z.object({
  version: z.number().int().positive(),
  groups: z.array(groupSchema),
  brokers: z.array(brokerSchema),
});

export const registryCatalogSchema = z.object({
  sourceUrl: httpsUrl,
  retrievedAt: isoDate,
  snapshotFile: z.string(),
  brokers: z.array(brokerSchema),
});

export const idAliasesSchema = z.record(z.string(), z.string());

export interface ParsedCatalog {
  groups: BrokerGroup[];
  brokers: CatalogBroker[];
  aliases: Record<string, string>;
}

/**
 * Validate the curated catalog, the registry catalog and the alias map together.
 * Throws with every problem listed, so a bad data edit fails at import (and in CI).
 */
export function parseCatalog(curated: unknown, registry: unknown, aliases: unknown): ParsedCatalog {
  const c = curatedCatalogSchema.parse(curated);
  const r = registryCatalogSchema.parse(registry);
  const a = idAliasesSchema.parse(aliases);
  const problems: string[] = [];

  for (const b of c.brokers) {
    if (b.source !== "curated") problems.push(`${b.id}: brokers.json entries must be source=curated`);
  }
  for (const b of r.brokers) {
    if (b.source !== "cppa_registry") problems.push(`${b.id}: registry entries must be source=cppa_registry`);
  }

  const groupIds = new Set(c.groups.map((g) => g.id));
  const brokers = [...c.brokers, ...r.brokers];
  const ids = new Set<string>();
  for (const b of brokers) {
    if (ids.has(b.id)) problems.push(`duplicate broker id ${b.id}`);
    ids.add(b.id);
    if (b.parentGroup && !groupIds.has(b.parentGroup)) {
      problems.push(`${b.id}: unknown parentGroup ${b.parentGroup}`);
    }
  }
  for (const [oldId, newId] of Object.entries(a)) {
    if (ids.has(oldId)) problems.push(`alias ${oldId} shadows a live broker id`);
    if (!ids.has(newId)) problems.push(`alias ${oldId} → ${newId} points at no broker`);
  }

  if (problems.length) throw new Error(`Invalid broker catalog:\n- ${problems.join("\n- ")}`);
  return { groups: c.groups, brokers, aliases: a };
}
