import type { ConnectorType } from "@/lib/connectors/types";
import type { SkillCatalogEntry, WorkflowSkillDef } from "./types";

/** Hermes pipeline — matches real case status transitions (classify/route run inline). */
export const WORKFLOW_SKILLS: WorkflowSkillDef[] = [
  {
    skillId: "intake-and-consent",
    label: "Intake & consent",
    workflowOrder: 1,
    afterStatus: ["draft"],
  },
  {
    skillId: "discover-public-exposure",
    label: "Discover exposures",
    workflowOrder: 2,
    afterStatus: ["consent_verified", "candidate_review"],
  },
  {
    skillId: "verify-identity-match",
    label: "Verify identity match",
    workflowOrder: 3,
    afterStatus: ["candidate_review"],
  },
  {
    skillId: "resolve-content-controller",
    label: "Resolve controller",
    workflowOrder: 4,
    afterStatus: ["confirmed_exposure", "controller_resolution"],
  },
  {
    skillId: "draft-removal-request",
    label: "Draft removal request",
    workflowOrder: 5,
    afterStatus: ["remedy_selected"],
  },
  {
    skillId: "compliance-verify-draft",
    label: "Compliance verify draft",
    workflowOrder: 6,
    afterStatus: ["draft_ready"],
  },
  {
    skillId: "record-outbound-sent",
    label: "Record outbound sent",
    workflowOrder: 7,
    afterStatus: ["approved_to_send", "user_review"],
  },
  {
    skillId: "schedule-monitoring",
    label: "Schedule monitoring",
    workflowOrder: 8,
    afterStatus: ["sent"],
  },
  {
    skillId: "verify-removal",
    label: "Verify removal",
    workflowOrder: 9,
    afterStatus: ["verification_due", "reopened"],
  },
  {
    skillId: "follow-up-policy",
    label: "Follow-up policy",
    workflowOrder: 10,
    afterStatus: ["follow_up_eligible"],
  },
];

const discoveryConnectors: ConnectorType[] = ["serpapi", "bing_search", "google_cse"];
const intelligenceConnectors: ConnectorType[] = ["openai", "anthropic", "openrouter"];
const emailConnectors: ConnectorType[] = ["gmail", "smtp", "resend", "sendgrid", "postmark"];

export const SKILL_CATALOG: Record<string, SkillCatalogEntry> = {
  "intake-and-consent": {
    id: "intake-and-consent",
    category: "workflow",
    phase: "intake",
    workflowOrder: 1,
    summary: "Create and validate authorized privacy cases before any discovery.",
    automatable: false,
    implementedInApp: true,
    nextSkills: ["discover-public-exposure"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["draft"],
  },
  "discover-public-exposure": {
    id: "discover-public-exposure",
    category: "workflow",
    phase: "discovery",
    workflowOrder: 2,
    summary: "Search approved public sources and create exposure candidates.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["verify-identity-match"],
    optionalConnectors: discoveryConnectors,
    requiredConnectors: [],
    triggerStatuses: ["consent_verified", "discovery_running", "candidate_review"],
  },
  "intake-live-url": {
    id: "intake-live-url",
    category: "operational",
    phase: "discovery",
    summary: "Add a user-supplied public URL via SSRF-safe fetch and evidence capture.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["verify-identity-match"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["consent_verified", "candidate_review", "confirmed_exposure"],
  },
  "verify-identity-match": {
    id: "verify-identity-match",
    category: "workflow",
    phase: "matching",
    workflowOrder: 3,
    summary: "Score and review whether candidates belong to the authorized person.",
    automatable: false,
    implementedInApp: true,
    nextSkills: ["resolve-content-controller"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["candidate_review"],
  },
  "classify-exposure": {
    id: "classify-exposure",
    category: "operational",
    phase: "classification",
    summary: "Rules-based classification of exposure type and risk (runs inline on confirm; LLM optional for draft polish only).",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["resolve-content-controller"],
    optionalConnectors: intelligenceConnectors,
    requiredConnectors: [],
    triggerStatuses: ["confirmed_exposure"],
  },
  "resolve-content-controller": {
    id: "resolve-content-controller",
    category: "workflow",
    phase: "remediation",
    workflowOrder: 4,
    summary: "Find official contacts, opt-out pages, and reporting channels (includes classify + route).",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["draft-removal-request"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["confirmed_exposure", "controller_resolution"],
  },
  "route-remedy": {
    id: "route-remedy",
    category: "operational",
    phase: "remediation",
    summary: "Select the official removal path (runs inline during controller resolution).",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["draft-removal-request"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["controller_resolution", "remedy_selected"],
  },
  "draft-removal-request": {
    id: "draft-removal-request",
    category: "workflow",
    phase: "correspondence",
    workflowOrder: 5,
    summary: "Generate factual, editable removal requests from verified evidence.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["compliance-verify-draft"],
    optionalConnectors: intelligenceConnectors,
    requiredConnectors: [],
    triggerStatuses: ["remedy_selected", "draft_ready"],
  },
  "compliance-verify-draft": {
    id: "compliance-verify-draft",
    category: "workflow",
    phase: "correspondence",
    workflowOrder: 6,
    summary: "Rules-based compliance check for prohibited language and missing facts (LLM optional for draft polish only).",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["record-outbound-sent"],
    optionalConnectors: intelligenceConnectors,
    requiredConnectors: [],
    triggerStatuses: ["draft_ready", "user_review"],
  },
  "record-outbound-sent": {
    id: "record-outbound-sent",
    category: "workflow",
    phase: "correspondence",
    workflowOrder: 7,
    summary: "Record that the user sent a draft via mail client, copy, or Gmail.",
    automatable: false,
    implementedInApp: true,
    nextSkills: ["schedule-monitoring"],
    optionalConnectors: emailConnectors,
    requiredConnectors: [],
    triggerStatuses: ["approved_to_send", "user_review", "draft_ready"],
  },
  "batch-remediation": {
    id: "batch-remediation",
    category: "operational",
    phase: "remediation",
    summary: "Resolve controllers and create drafts for multiple exposures in one pass.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["compliance-verify-draft"],
    optionalConnectors: intelligenceConnectors,
    requiredConnectors: [],
    triggerStatuses: ["confirmed_exposure", "controller_resolution", "remedy_selected"],
  },
  "verify-removal": {
    id: "verify-removal",
    category: "workflow",
    phase: "verification",
    workflowOrder: 9,
    summary: "Check whether exposures remain publicly visible after remediation.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["follow-up-policy", "generate-removal-certificate"],
    optionalConnectors: discoveryConnectors,
    requiredConnectors: [],
    triggerStatuses: ["sent", "verification_due", "reopened"],
  },
  "schedule-monitoring": {
    id: "schedule-monitoring",
    category: "workflow",
    phase: "verification",
    workflowOrder: 8,
    summary: "Schedule recurring verification checks for confirmed exposures.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["verify-removal"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["sent", "verification_due", "removed_confirmed"],
  },
  "follow-up-policy": {
    id: "follow-up-policy",
    category: "workflow",
    phase: "correspondence",
    workflowOrder: 10,
    summary: "Create policy-gated follow-up drafts when controllers do not respond.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["verify-removal"],
    optionalConnectors: emailConnectors,
    requiredConnectors: [],
    triggerStatuses: ["follow_up_eligible"],
  },
  "reopen-on-reappearance": {
    id: "reopen-on-reappearance",
    category: "operational",
    phase: "verification",
    summary: "Reopen resolved cases when information reappears on public sources.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["resolve-content-controller"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["removed_confirmed", "partially_resolved"],
  },
  "generate-removal-certificate": {
    id: "generate-removal-certificate",
    category: "operational",
    phase: "verification",
    summary: "Export an auditable removal certificate after verified removal.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["export-case-packet"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["removed_confirmed"],
  },
  "export-case-packet": {
    id: "export-case-packet",
    category: "operational",
    phase: "operations",
    summary: "Export redacted case packet JSON for legal or advocacy review.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["escalate-legal-review"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["draft", "sent", "removed_confirmed", "escalated"],
  },
  "escalate-legal-review": {
    id: "escalate-legal-review",
    category: "operational",
    phase: "operations",
    summary: "Prepare a legal-review escalation packet when official channels fail (template + export only).",
    automatable: false,
    implementedInApp: false,
    nextSkills: ["export-case-packet"],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: ["follow_up_eligible", "escalated", "partially_resolved"],
  },
  "connector-readiness-check": {
    id: "connector-readiness-check",
    category: "onboarding",
    phase: "onboarding",
    summary: "Verify BYOK connectors are configured before live discovery or outbound email.",
    automatable: true,
    implementedInApp: true,
    nextSkills: ["discover-public-exposure"],
    optionalConnectors: [...discoveryConnectors, ...intelligenceConnectors, ...emailConnectors],
    requiredConnectors: [],
    triggerStatuses: [],
  },
  "sentinel-security-auditor": {
    id: "sentinel-security-auditor",
    category: "security",
    phase: "security",
    summary: "Developer-only security scans for ClearTrace-owned assets.",
    automatable: true,
    implementedInApp: true,
    nextSkills: [],
    optionalConnectors: [],
    requiredConnectors: [],
    triggerStatuses: [],
  },
};

export function getCatalogEntry(skillId: string): SkillCatalogEntry | null {
  return SKILL_CATALOG[skillId] ?? null;
}

export function getWorkflowSkillIds(): string[] {
  return WORKFLOW_SKILLS.map((s) => s.skillId);
}

/**
 * Maps case status → index in WORKFLOW_SKILLS (current recommended step).
 * Classify + route run inline; indices skip those as separate Hermes steps.
 */
export const STATUS_INDEX: Record<string, number> = {
  draft: 0,
  consent_verified: 1,
  scan_queued: 1,
  discovery_running: 1,
  candidate_review: 2,
  confirmed_exposure: 3,
  controller_resolution: 3,
  remedy_selected: 4,
  draft_ready: 5,
  user_review: 6,
  approved_to_send: 6,
  sent: 7,
  awaiting_response: 7,
  verification_due: 8,
  reopened: 8,
  partially_resolved: 8,
  removed_confirmed: 9,
  follow_up_eligible: 9,
  escalated: 9,
  closed: 10,
  paused: -1,
  archived: -1,
};